Repository spotseeker/app, pull requests merged in 2024-11, with the labels that each got.

#40 features/12/search-view
  .husky/pre-commit
  src/app/(tabs)/Search.tsx
  src/app/(tabs)/_layout.tsx
  src/app/(tabs)/search.tsx
  src/app/auth/login.tsx
  src/app/auth/password/index.tsx
  src/app/auth/password/otp.tsx
  src/app/auth/password/reset.tsx
  src/components/ImageGrid.tsx
  src/components/Input.tsx
  src/components/SearchInput.tsx
  src/fixtures/images.ts
  src/screens/signup/steps.tsx
Labels: enhancement

#45 features/18/map-view
  android/.gitignore
  android/app/build.gradle
  android/app/debug.keystore
  android/app/proguard-rules.pro
  android/app/src/debug/AndroidManifest.xml
  android/app/src/main/AndroidManifest.xml
  android/app/src/main/java/com/daragoucla/spotseeker/MainActivity.kt
  android/app/src/main/java/com/daragoucla/spotseeker/MainApplication.kt
  android/app/src/main/res/drawable-hdpi/splashscreen_image.png
  android/app/src/main/res/drawable-mdpi/splashscreen_image.png
  android/app/src/main/res/drawable-xhdpi/splashscreen_image.png
  android/app/src/main/res/drawable-xxhdpi/splashscreen_image.png
  android/app/src/main/res/drawable-xxxhdpi/splashscreen_image.png
  android/app/src/main/res/drawable/rn_edit_text_material.xml
  android/app/src/main/res/drawable/splashscreen.xml
  android/app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml
  android/app/src/main/res/mipmap-anydpi-v26/ic_launcher_round.xml
  android/app/src/main/res/mipmap-hdpi/ic_launcher.png
  android/app/src/main/res/mipmap-hdpi/ic_launcher_foreground.png
  android/app/src/main/res/mipmap-hdpi/ic_launcher_round.png
  android/app/src/main/res/mipmap-mdpi/ic_launcher.png
  android/app/src/main/res/mipmap-mdpi/ic_launcher_foreground.png
  android/app/src/main/res/mipmap-mdpi/ic_launcher_round.png
  android/app/src/main/res/mipmap-xhdpi/ic_launcher.png
  android/app/src/main/res/mipmap-xhdpi/ic_launcher_foreground.png
  android/app/src/main/res/mipmap-xhdpi/ic_launcher_round.png
  android/app/src/main/res/mipmap-xxhdpi/ic_launcher.png
  android/app/src/main/res/mipmap-xxhdpi/ic_launcher_foreground.png
  android/app/src/main/res/mipmap-xxhdpi/ic_launcher_round.png
  android/app/src/main/res/mipmap-xxxhdpi/ic_launcher.png
  android/app/src/main/res/mipmap-xxxhdpi/ic_launcher_foreground.png
  android/app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.png
  android/app/src/main/res/values-night/colors.xml
  android/app/src/main/res/values/colors.xml
  android/app/src/main/res/values/strings.xml
  android/app/src/main/res/values/styles.xml
  android/build.gradle
  android/gradle.properties
  android/gradle/wrapper/gradle-wrapper.jar
  android/gradle/wrapper/gradle-wrapper.properties
  android/gradlew
  android/gradlew.bat
  android/react-settings-plugin/build.gradle.kts
  android/react-settings-plugin/src/main/kotlin/expo/plugins/ReactSettingsPlugin.kt
  android/settings.gradle
  app.json
  package-lock.json
  package.json
  src/app/(tabs)/MapView.tsx
  src/app/(tabs)/_layout.tsx
  src/app/(tabs)/map.tsx
  src/app/profile/password.tsx
  src/components/Icons.tsx
  src/components/SearchInput.tsx
Labels: enhancement, help wanted

#63 hotfix/add-pagination-support
  src/api/client.ts
  src/api/post.ts
Labels: bug

#64 integrated login service
  package-lock.json
  package.json
  src/api/auth.ts
  src/app/_layout.tsx
  src/app/auth/_layout.tsx
  src/app/auth/login.tsx
  src/app/profile/settings.tsx
  src/components/Button.tsx
  src/context/context.tsx
  src/hooks/useAuth.ts
Labels: enhancement

#66 hotfix/enviroment-variables
  .env.example
  package-lock.json
  src/settings/settings.ts
Labels: bug
